import type { Collection } from 'tinacms';

export const projectCollection: Collection = {
  name: 'project',
  label: 'Projects',
  path: 'src/content/projects',
  format: 'md',
  ui: { router: ({ document }) => `/projects/${document._sys.filename}/` },
  fields: [
    { name: 'title', label: 'Project title', type: 'string', isTitle: true, required: true },
    { name: 'englishTitle', label: 'Subtitle / English title', type: 'string', required: true },
    { name: 'category', label: 'Category', type: 'string', options: [{ value: 'agent-world', label: 'Agent Worlds' }, { value: 'holistic-assistant', label: 'Holistic Assistant' }, { value: 'ai-tools', label: 'AI + Tools' }], required: true },
    { name: 'repositoryVisibility', label: 'Repository visibility', type: 'string', options: ['public', 'private'], required: true },
    { name: 'visual', label: 'Project visual', type: 'string', options: [{ value: 'campus', label: 'Campus / product image' }, { value: 'pipeline', label: 'Technical pipeline' }], required: true },
    { name: 'technicalTitle', label: 'Implementation heading', type: 'string', required: true },
    { name: 'order', label: 'Project order', type: 'number' },
    { name: 'status', label: 'Current status', type: 'string', required: true },
    { name: 'statusDetail', label: 'Status detail', type: 'string', required: true, ui: { component: 'textarea' } },
    { name: 'description', label: 'Short description', type: 'string', required: true, ui: { component: 'textarea' } },
    { name: 'summary', label: 'Project-list summary', type: 'string', required: true, ui: { component: 'textarea' } },
    { name: 'liveUrl', label: 'Live URL (optional)', type: 'string' },
    { name: 'githubUrl', label: 'GitHub URL', type: 'string', required: true },
    { name: 'launched', label: 'Started / timeline', type: 'string', required: true },
    { name: 'lastVerified', label: 'Last source/documentation audit', type: 'datetime', required: true },
    { name: 'heroImage', label: 'Hero image (optional for pipeline projects)', type: 'image' },
    { name: 'heroAlt', label: 'Hero image alt text', type: 'string' },
    { name: 'pipeline', label: 'Technical pipeline', type: 'object', list: true, fields: [
      { name: 'title', label: 'Step', type: 'string', required: true },
      { name: 'detail', label: 'Detail', type: 'string', required: true },
    ] },
    { name: 'engineering', label: 'Engineering notes', type: 'object', list: true, fields: [
      { name: 'title', label: 'Question / decision', type: 'string', required: true },
      { name: 'detail', label: 'Implementation and rationale', type: 'string', required: true, ui: { component: 'textarea' } },
    ] },
    { name: 'evidence', label: 'Public code / verification links', type: 'object', list: true, fields: [
      { name: 'label', label: 'Label', type: 'string', required: true },
      { name: 'url', label: 'URL', type: 'string', required: true },
    ] },
    {
      name: 'metrics',
      label: 'Project metrics',
      type: 'object',
      list: true,
      fields: [
        { name: 'value', label: 'Value', type: 'string', required: true },
        { name: 'label', label: 'Label', type: 'string', required: true },
        { name: 'note', label: 'Verification note', type: 'string' },
      ],
    },
    {
      name: 'features',
      label: 'Features',
      type: 'object',
      list: true,
      fields: [
        { name: 'index', label: 'Index', type: 'string', required: true },
        { name: 'title', label: 'Title', type: 'string', required: true },
        { name: 'description', label: 'Description', type: 'string', required: true, ui: { component: 'textarea' } },
      ],
    },
    { name: 'principles', label: 'Principles / caveats', type: 'string', list: true },
    { name: 'stack', label: 'Technology stack', type: 'string', list: true },
    { name: 'body', label: 'Project body', type: 'rich-text', isBody: true },
  ],
};
